# Generated by Django 4.2.16 on 2024-09-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='other', max_length=100),
            preserve_default=False,
        ),
    ]
