# Generated by Django 4.2.16 on 2024-09-24 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('FR', 'Fresh Produce'), ('DA', 'Dairy'), ('MP', 'Meat and Poultry'), ('SF', 'Seafood'), ('FRZ', 'Frozen Foods'), ('BK', 'Bakery'), ('BV', 'Beverages'), ('CPG', 'Canned and Packaged Goods'), ('DG', 'Dry Goods & Grains'), ('SN', 'Snacks'), ('BR', 'Breakfast Items'), ('CS', 'Condiments and Sauces'), ('SS', 'Spices and Seasonings'), ('BCI', 'Baking and Cooking Ingredients'), ('EF', 'Ethnic Foods'), ('HW', 'Health & Wellness'), ('HC', 'Household and Cleaning'), ('BCC', 'Baby & Child Care'), ('PC', 'Personal Care'), ('PTC', 'Pet Care'), ('OTH', 'Other')], default='OTH', max_length=4),
        ),
    ]
