# Generated by Django 4.2.16 on 2024-09-25 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_item_user_alter_item_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['added_at']},
        ),
    ]
